### PR TITLE
Rename scripts

### PR DESCRIPTION
**Pull request by abc013**
Quick and clean rename campaign.

This was not committed directly because this could create a lot of rebase conflicts with other parts in other branches.

All my following PRs are based on this one.

### CODE REVIEW

**Comment by abc013** [comment]
Updated to adjust to your suggestions. Just leave a message if something bothers you.

**Comment by Wolkenfarmer** [comment]
Why `WaveUnit` instead of `Unit`?
This class should theoretically be able to group all sort of things into one unit.. it's just specified for enemy ships right now and only gets used in the endless wave controller.

Why did you add `[...]Helper` to the `ScreenboundsKiller` and `ScreenClamp`? Wouldn't the names be also sufficient without out this part?

In addition, wouldn't "Rename scripts" be enough as name for this PR?

The rest seems fine to me and works.

**Comment by abc013** [comment]
> Why `WaveUnit` instead of `Unit`?

Because that's its job right now and it is also implemented for enemies. Also, we probably wouldn't need it for anything else. This is why specifying here imo would actually help understanding the code.

> Why did you add [...]Helper to the ScreenboundsKiller and ScreenClamp? Wouldn't the names be also sufficient without out this part?

Because they are indeed only helpers and are only checking some quite simple boundary checks we could have done in `Spaceship` and `Bullet` as well. Obviously, we outsourced them and I personally see them as helper classes. I don't know about both of you, but we can change that if you want to.

> In addition, wouldn't "Rename scripts" be enough as name for this PR?

Right, sorry, forgot to update the title.

**Comment by Wolkenfarmer** [comment]
> Because that's its job right now and it is also implemented for enemies. Also, we probably wouldn't need it for anything else. This is why specifying here imo would actually help understanding the code.

Okay, but wouldn `EnemyUnit` be more logical then?


> Because they are indeed only helpers and are only checking some quite simple boundary checks we could have done in Spaceship and Bullet as well. Obviously, we outsourced them and I personally see them as helper classes.

Hm, understandable.. however, I would remove the `helper` part, because they indeed kill at the screen bound and not just helpto kill them there.. therefore it would either be `KillHelper` or `ScreenboundsKiller` for example in my opinion, while I prefer the second one (more information)


> Right, sorry, forgot to update the title.

👍

**Comment by abc013** [comment]
> Okay, but wouldn `EnemyUnit` be more logical then?

Would there be any `FriendlyUnit`? ;)
I did go a bit too far, sorry. The thing is that Unit is strongly connected with the WaveController and actually kind of represents the wave of enemies. In that matter the name makes more sense.

> Hm, understandable.. however, I would remove the helper part, because they indeed kill at the screen bound and not just helpto kill them there.. therefore it would either be `KillHelper` or `ScreenboundsKiller` for example in my opinion, while I prefer the second one (more information)

I see, and i also like the second one. :+1: will update soon.

**Comment by Wolkenfarmer** [comment]
> I did go a bit too far, sorry. The thing is that Unit is strongly connected with the WaveController and actually kind of represents the wave of enemies. In that matter the name makes more sense

Okay, if you mean so :)


> I see, and I also like the second one. 👍 will update soon.

👍

**Comment by abc013** [comment]
Updated. Other PRs are currently updated.

**Pull request merged**
